name: Auto Push

on:
  schedule:
    - cron: '40 13 * * *' # 毎日13時30分（UTC）に実行

jobs:
  auto-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Update file
        run: |
          echo "Updated at $(date)" > update_log.txt

      - name: Commit and push
        run: |
          git config --local user.email "${{ secrets.USER_EMAIL }}"
          git config --local user.name "${{ secrets.USER_NAME }}"
          git add update_log.txt
          git commit -m "Automated update at $(date)" || echo "No changes to commit"
          git push origin HEAD
